version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - misspell
    - unconvert
    - gosec
  exclusions:
    rules:
      # G304: file path from variable — intentional for a CLI tool that reads
      # user-specified config, targets, and PID files.
      - linters: [gosec]
        text: "G304"

formatters:
  enable:
    - gofmt
    - goimports

issues:
  # Don't report the same issue more than once
  max-same-issues: 0
